<?php

namespace Kiri\Rpc\Annotation;

use Annotation\Attribute;
use Http\Handler\Router;
use Kiri\Kiri;

#[\Attribute(\Attribute::TARGET_CLASS)] class JsonRpc extends Attribute
{


	/**
	 * @param string $method
	 * @param string $version
	 */
	public function __construct(public string $method, public string $version = '2.0', public string $protocol = 'json')
	{

	}


	/**
	 * @param mixed $class
	 * @param mixed|string $method
	 * @return mixed
	 */
	public function execute(mixed $class, mixed $method = ''): mixed
	{
		return parent::execute($class, $method); // TODO: Change the autogenerated stub
	}


}
